Feature/view home
frontendcafe/cmyk-mango pull request #131
Opened 2021-12-01 19:28 UTC by isma-morel

Rutas añadidas, handlers redirect añadidos a los botones. Mq añadida.

2021-12-01 19:56 UTC, franmper requested changes
El resto muy bien!

2021-12-01 19:56 UTC, franmper commented on src/router/routes.js
> +    component: Home2,
No entiendo muy bien esto, deberia ser una home nomas

2021-12-01 19:56 UTC, franmper commented on src/components/AuthLayout/AuthLayout.jsx
> +    const {push} = useHistory()
probablemente no tengas instalado prettier puede ser? por que aca deberia ser algo como ```const { push } = useHistory()```

2021-12-01 19:56 UTC, franmper commented on .prettierrc
> +}
No se por que te esta tomando estos cambios cuando ya los mergeamos, no se si es un error de github o algo raro paso. Probablemente en el proximo commit se arreglue por que tambien es muy raro que no tire conflictos por esto

2021-12-01 21:05 UTC, isma-morel commented on src/components/AuthLayout/AuthLayout.jsx
> +    const {push} = useHistory()
Lo tengo instalado pero no me lo toma, es muy raro eso, tambien tengo el settings.json de visual configurado

2021-12-01 21:05 UTC, isma-morel commented on src/router/routes.js
> +    component: Home2,
Configure la ruta para que tome la home de verdad, la otra dijo leo que era para que veamos que componentes ya estaban hechos, decis que la saque directamente y deje la home original?

2021-12-01 21:40 UTC, isma-morel commented
Fix realizado.

2021-12-01 22:51 UTC, franmper commented on src/components/AuthLayout/AuthLayout.jsx
> +    const {push} = useHistory()
mmm que raro, si apretas ctrl + shift + L o I no recuerdo 100% cual era pero uno de esos deberia formatearte. O click derecho format document. Ahi deberia hacertelo.

2021-12-01 22:51 UTC, franmper commented on src/router/routes.js
> +    component: Home2,
Yo no lo pondria en el routes, de ultima al archivo ponele Example.js o algo asi, para no confundir

2021-12-02 13:53 UTC, SebasEC96 approved these changes
LGTM

2021-12-02 13:57 UTC, franmper approved these changes

2021-12-03 18:47 UTC, merged