Feature/login
frontendcafe/cmyk-mango pull request #24
Opened 2021-09-08 01:32 UTC by lucianina1994

Peticion para fusionar feature/login con main.

2021-09-09 14:26 UTC, MatiasOlivera requested changes

2021-09-09 14:26 UTC, MatiasOlivera commented on css/login.css
> +    justify-content: space-between
Hay mucho espacio entre "¿No tenes cuenta?" y el botón "Crear cuenta"
![sin-cuenta](https://user-images.githubusercontent.com/16739011/132702427-8af382c1-0a47-4347-b8f6-5e201aae9437.png)


A la clase `form-footer` le podes cambiar la propiedad flex a `justify-content: center` y a `form-footer__p` le podes agregar un `margin: 1em`.

2021-09-09 14:26 UTC, MatiasOlivera commented on js/login.js
> +    <h3 class="form__title">¡Bievenidx!</h3>
Se debería usar la etiqueta `h1` en vez de la `h3`.

Hay que evitar omitir niveles de títulos: primero usar h1, después h2 y así sucesivamente.

2021-09-09 14:26 UTC, MatiasOlivera commented on js/index.js
> +  formularioInicio.style.display = "none";
Una vez que esten todos los cambios, ¿podrías hacer que por defecto se muestre la sección de inicio? El formulario de login no debería mostrarse por defecto. Entiendo que lo estuviste usando de esa manera para desarrollar, pero en la versión remota (Github) no debería quedar de esa forma

2021-09-09 14:32 UTC, MatiasOlivera requested changes

2021-09-09 14:32 UTC, MatiasOlivera commented on js/login.js
> +    <h3 class="form__title">¡Bievenidx!</h3>
Hay un typo en "¡Bievenidx!", le falta la n

2021-09-09 14:32 UTC, MatiasOlivera commented on js/login.js
> +  <div class="form-header">
El fondo de la versión mobile debería ser blanco, actualmente está usando el color secundario

2021-09-09 18:34 UTC, lucianina1994 commented on css/login.css
> +    justify-content: space-between
Listo! Lo que si hice diferente fue poner `margin: 0 1em` porque el tamaño de las fuentes son diferentes

2021-09-09 18:37 UTC, lucianina1994 commented on js/index.js
> +  formularioInicio.style.display = "none";
Sii tuve problemas con eso, yo queria revertirlo y se ve que se envio igual, creo que hice mal los pasos luego del  `git reset --soft HEAD~1 ` ahora lo resuelvo

2021-09-09 19:00 UTC, lucianina1994 commented
@MatiasOlivera Como hago para subir mis nuevos cambios? Cierro este PR y hago un nuevo PR?

2021-09-10 15:27 UTC, MatiasOlivera commented on js/index.js
> +  formularioInicio.style.display = "none";
Ah, esta bien, suele pasar

2021-09-10 15:43 UTC, MatiasOlivera commented on js/login.js
> +  <div class="form-header">
El color de fondo es cyan pero debería ser blanco. La única diferencia entre ambos diseños debería ser el logo de la app, ya que se va a ocultar mediante Javascript

Resultado obtenido:
![login](https://user-images.githubusercontent.com/16739011/132879775-cb3d7436-8a04-4bff-8e14-d486eabafaa3.png)

Resultado esperado:
![login-diseño](https://user-images.githubusercontent.com/16739011/132879739-f5e1214b-0eea-427a-9ed6-6fd4c727fd5c.png)

2021-09-10 18:55 UTC, lucianina1994 commented on js/login.js
> +  <div class="form-header">
Claro ahi esta mi duda, ese color del fondo depende de .welcome que involucra mi seccion y otras dos mas, te parece que haga esa modificacion en index.css? o corregime si me equivoco
![image](https://user-images.githubusercontent.com/70176352/132903277-8bcb007d-fcbb-4971-b765-83f962f17d24.png)

2021-09-11 20:19 UTC, MatiasOlivera commented on js/login.js
> +  <div class="form-header">
Me di cuenta que el cambio de color de fondo no se puede hacer usando solamente CSS, sino que se debe utilizar Javascript también. Cuando el usuario haga click en el botón "Iniciar sesión" o "Registro" se debería cambiar el color de fondo del formulario modificando la clase .`welcome`

2021-09-11 20:19 UTC, merged

2021-09-11 20:20 UTC, MatiasOlivera commented
Buenísimo @lucianina1994 ! :tada: