barra de navegacion
frontendcafe/cmyk-mango pull request #25
Opened 2021-09-08 20:18 UTC by luciabrumnich

2021-09-09 15:43 UTC, MatiasOlivera requested changes

2021-09-09 15:43 UTC, MatiasOlivera commented on navegacion.html
> +    <link rel="stylesheet" href="./css/primeros-pasos.css">
Se deberían eliminar los estilos CSS que no usados.

```
<link rel="stylesheet" href="./css/primeros-pasos.css">
<link rel="stylesheet" href="./css/login.css">
<link rel="stylesheet" href="./css/registro.css">
```

2021-09-09 15:43 UTC, MatiasOlivera commented on navegacion.html
> +    <script src="./js/primeros-pasos.js" type="module"></script>
Se deberían eliminar los scripts que no son usados.

```
<script src="./js/primeros-pasos.js" type="module"></script>
<script src="./js/login.js" type="module"></script>
<script src="./js/registro.js" type="module"></script>
```

2021-09-09 15:43 UTC, MatiasOlivera commented on navegacion.html
> +        <a id="bell" href=""><img src="../assets/img/bell.svg" alt=""></a>
Se debería agregar el texto alternativo "Notificaciones" para la campana y "Menu" para las 3 líneas

2021-09-09 15:43 UTC, MatiasOlivera commented on navegacion.html
> +  <header class="container header">
¿Podrías agregar la barra de navegación al `index.html`? Hay que copiar/pegar el HTML e importar el archivo `navegacion.css`

2021-09-09 15:43 UTC, MatiasOlivera commented on css/navegacion.css
> +:root {
Eliminar los estilos de la línea 1 a la 23 porque ya están definidos en el archivo `index.css` y son estilos comunes a toda la aplicación

2021-09-09 15:43 UTC, MatiasOlivera commented on navegacion.html
> +  <nav class="nav">
La línea que separa los elementos del menú debería ocupar todo el ancho del contenedor. Actualmente depende del ancho del texto

![menu](https://user-images.githubusercontent.com/16739011/132718065-1e51cd15-ff9a-4560-b181-5df2d8e9fd5a.png)

2021-09-09 16:48 UTC, luciabrumnich commented on navegacion.html
> +  <nav class="nav">
Si, lo noté. Pero como estaba hecho ya, lo dejé así. Debería haber preguntado por las dudas igualmente. Busqué como modificarlo y no lo encontré. Consulto por el grupo.

2021-09-09 17:12 UTC, luciabrumnich commented on navegacion.html
> +  <header class="container header">
El index.html ya tiene una barra de navegación, es distinta. Cómo la agregaría?

2021-09-10 15:54 UTC, MatiasOlivera commented on navegacion.html
> +  <header class="container header">
Tenés razón, hace de cuenta que no dije nada jaja

2021-09-10 16:10 UTC, MatiasOlivera commented on navegacion.html
> +  <nav class="nav">
No te hagas problema en preguntar lo que sea.

>  Busqué como modificarlo y no lo encontré

Si queres después nos reunimos un momento y lo vemos

2021-09-10 16:13 UTC, luciabrumnich commented on navegacion.html
> +  <header class="container header">
Ah ok jaja, perfecto. Esta barra sería para las páginas siguientes entiendo.

2021-09-10 16:32 UTC, luciabrumnich commented on navegacion.html
> +    <script src="./js/primeros-pasos.js" type="module"></script>
primeros-pasos.js lo dejo porque lo usa para desplegar el menu del nav mobile. Está bien así o debería realizar algún cambio? Había dado por resuelta la conversación, pero me acabo de dar cuenta de esto.

2021-09-10 18:46 UTC, MatiasOlivera commented on navegacion.html
> +    <script src="./js/primeros-pasos.js" type="module"></script>
El código para desplegar el menu debería ir en un archivo `navegacion.js` porque el navbar se va a usar en muchas partes de la app, no solo en la paǵina de inicio.

Lo que podes hacer es:
- Crear un archivo `navegacion.js` con el código de `primeros-pasos.js`
- Renombrar `primeros-pasos.js` como `inicio.js`
- Importar el archivo `navegacion.js` en vez de `inicio.js` en `navegacion.html`

2021-09-10 18:51 UTC, luciabrumnich commented on navegacion.html
> +  <nav class="nav">
Resuelto.

2021-09-10 18:57 UTC, luciabrumnich commented on navegacion.html
> +    <script src="./js/primeros-pasos.js" type="module"></script>
Si renombro el archivo como inicio.js, pienso que no, pero por las dudas pregunto, no crearía conflicto en otro lado?

2021-09-10 20:38 UTC, MatiasOlivera commented on navegacion.html
> +    <script src="./js/primeros-pasos.js" type="module"></script>
El archivo `inicio.js` solo debería usarse en el `index.html` y no debería importarse desde otro HTML, por lo que no habria problema.

2021-09-10 20:42 UTC, MatiasOlivera commented on navegacion.html
> +    <script src="./js/primeros-pasos.js" type="module"></script>
Me parece que ese cambio queda fuera del scope de este ticket, así que voy a aceptar los cambios actuales

2021-09-10 20:54 UTC, MatiasOlivera requested changes

2021-09-10 20:54 UTC, MatiasOlivera commented on navegacion.html
> +    <ul class="menu">
Los links de la barra de navegación deberían ocupar una sola línea, actualmente usan dos líneas.

![navbar](https://user-images.githubusercontent.com/16739011/132916113-0fa1232f-3c13-45cb-b069-8c9bdf46662a.png)

Podes hacer que los estilos de desktop y mobile sean diferentes usando media queries. Si no usas media queries, los estilos se aplican para todos los tamaños de pantalla

2021-09-11 20:35 UTC, MatiasOlivera commented
Genial @luciabrumnich ! :tada:

2021-09-11 20:36 UTC, merged