Feature/pagina mis reuniones
frontendcafe/cmyk-mango pull request #26
Opened 2021-09-09 01:02 UTC by leoachear

- Pantallas de "mis reuniones" versión Celular y Web.

![image](https://user-images.githubusercontent.com/7539443/132605094-9573492b-b7ed-463f-8573-7e2cefad30e8.png)

- Con nueva estructura de carpetas y archivos.
- Sin navbar ni footer (está en otro issue)

2021-09-11 21:10 UTC, MatiasOlivera requested changes

2021-09-11 21:10 UTC, MatiasOlivera commented on css/reuniones.css
> +  font-weight: 600;
La informacion de la reunión debería usar texto normal, no en negrita

![info-reunion](https://user-images.githubusercontent.com/16739011/132961673-520a8220-51b6-4b25-8653-2766526924f8.png)

2021-09-11 22:29 UTC, MatiasOlivera requested changes

2021-09-11 22:29 UTC, MatiasOlivera commented on js/reuniones.js
> +                <div class="meeting-item-desc">
Se podrían usar nombres más descriptivos en vez de abreviaciones, ya que a veces es dificil entender a qué se refiere la abreviación.

`meeting-item-desc` -> `meeting-item-description`

2021-09-11 22:29 UTC, MatiasOlivera commented on js/reuniones.js
> +                <div class="meeting-item-obs">
Se podrían usar nombres más descriptivos en vez de abreviaciones, ya que a veces es dificil entender a qué se refiere la abreviación.

`meeting-item-obs` -> `meeting-item-observation`

2021-09-11 22:29 UTC, MatiasOlivera commented on js/reuniones.js
> +}
Se debería borrar este código, porque no se usa en la página de Mis reuniones

2021-09-11 22:29 UTC, MatiasOlivera commented on js/no-meetings.js
> +// });
Se debería eliminar el código que no se usa

2021-09-13 14:18 UTC, leoachear commented
@MatiasOlivera  ahí quedaron resueltos los comentarios ¡Gracias! 👍

2021-09-14 19:53 UTC, MatiasOlivera commented
Excelente @leoachear! :tada:

2021-09-14 19:53 UTC, merged