Creada la Barra de navegación mobile
frontendcafe/cmyk-mango pull request #28
Opened 2021-09-09 15:06 UTC by leoachear

2021-09-11 15:53 UTC, leoachear commented
@MatiasOlivera ya agregué los estilos de las fuentes.

Ya sería la versión final.

2021-09-12 02:34 UTC, MatiasOlivera requested changes

2021-09-12 02:34 UTC, MatiasOlivera commented on navegacion-mobile.html
> +                <a id="new-meeting" href=""><img src="../assets/img/new-meeting.svg" alt=""></a>
La imagen debería tener el texto alternativo "Nueva reunión"

2021-09-12 02:34 UTC, MatiasOlivera commented on navegacion-mobile.html
> +                <a id="perfil" href=""><img src="../assets/img/perfil.svg" alt=""></a>
La imagen debería tener el texto alternativo "Perfil"

2021-09-12 02:34 UTC, MatiasOlivera commented on navegacion-mobile.html
> +                <a id="my-meetings" href=""><img src="../assets/img/my-meetings.svg" alt=""></a>
La imagen debería tener el texto alternativo "Mis reuniones"

2021-09-12 02:34 UTC, MatiasOlivera commented on css/navegacion-mobile.css
> +  flex-shrink: 0;
Se podrían eliminar estas propiedades ya que no se están usando y usar un padding en su lugar

2021-09-12 02:34 UTC, MatiasOlivera commented on css/navegacion-mobile.css
> +}
Se podrían eliminar las clases `.new-meeting`, `.perfil` y `.my-meetings` ya que la propiedad `text-align: center;` ya está definida en la clase `.footer .icons-footer`. También quitarlas del HTML

2021-09-12 02:34 UTC, MatiasOlivera commented on navegacion-mobile.html
> +    <footer class="footer">
El navbar mobile no debería verse en la versión desktop
![navbar-mobile-desktop](https://user-images.githubusercontent.com/16739011/132969512-ab1909b5-9c39-4b06-b852-a16ef70915a7.png)

2021-09-12 02:34 UTC, MatiasOlivera commented on navegacion-mobile.html
> +        <div class="icons-footer">
El navbar mobile debería aparecer fijo en la parte de abajo de la app (podes buscar "Navbar flotante" o "sticky navbar"). Actualmente hay que hacer scroll para ver el navbar
![navbar-mobile](https://user-images.githubusercontent.com/16739011/132969522-8d63280d-bef5-46cc-9fe5-980cb771a594.png)

2021-09-16 00:56 UTC, leoachear commented on css/navegacion-mobile.css
> +  flex-shrink: 0;
@MatiasOlivera no me queda claro como podría centrar los íconos verticalmente con padding 🤔

2021-09-16 01:07 UTC, leoachear commented on css/navegacion-mobile.css
> +}
@MatiasOlivera si le dejo solo al padre .footer .icons-footer el text-align: center; no me centra los hijos ¿Será porque es flex? 🤔

2021-09-19 17:49 UTC, MatiasOlivera requested changes

2021-09-19 17:49 UTC, MatiasOlivera commented on css/navegacion-mobile.css
> +  flex-shrink: 0;
Podrías eliminar estas propiedades de `.footer`, ya que al quitarlas no se nota una diferencia en la interfaz
```
  flex-direction: row;
  justify-content: space-around;
  align-items: center;
```

La clase que está posicionando a los iconos es `.footer .icons-footer`

2021-09-19 17:49 UTC, MatiasOlivera commented on css/navegacion-mobile.css
> +}
Si le agregas `text-align: center;` a `.footer .icons-footer` funciona. Lo probé en local

2021-09-21 12:16 UTC, leoachear commented on css/navegacion-mobile.css
> +  flex-shrink: 0;
Buenísimo, gracias 👍👍👍

2021-09-21 12:19 UTC, leoachear commented on css/navegacion-mobile.css
> +}
Gracias!!!

2021-09-22 01:37 UTC, MatiasOlivera approved these changes

2021-09-22 01:38 UTC, MatiasOlivera commented
Excelente Leo! :tada:

2021-09-22 01:38 UTC, merged