se agregaron los archivos descripcion.html y descripcion.css
frontendcafe/cmyk-mango pull request #40
Opened 2021-09-14 12:58 UTC by luciabrumnich

2021-09-19 19:44 UTC, MatiasOlivera requested changes

2021-09-19 19:44 UTC, MatiasOlivera commented on descripcion.html
> +            <h4>Título</h4>
Se debería usar la etiqueta `label` en vez de `h4` en los inputs

2021-09-19 19:44 UTC, MatiasOlivera commented on css/descripcion.css
> +.descripcion {
Se debería usar inglés para el nombre de los id y las clases

2021-09-22 15:53 UTC, luciabrumnich commented on descripcion.html
> +            <h4>Título</h4>
Hecho.

2021-09-22 15:54 UTC, luciabrumnich commented on css/descripcion.css
> +.descripcion {
Hechas las traducciones.

2021-09-23 15:50 UTC, MatiasOlivera approved these changes
Excelente Lucía! :tada:

2021-09-23 15:50 UTC, merged