Features/link component
frontendcafe/cmyk-mango pull request #89
Opened 2021-10-18 20:48 UTC by leoachear

Creado el Componente Link, se agregaron los estilos con CSS Modules.

2021-10-28 20:33 UTC, MatiasOlivera requested changes

2021-10-28 20:33 UTC, MatiasOlivera commented on src/components/LinkComponent/LinkComponent.module.css
> +.toLogin {
El nombre de la clase podría ser `link`, `toLogin` está relacionado a un link en particular y el nombre debería ser más general

2021-10-28 20:33 UTC, MatiasOlivera commented on src/components/LinkComponent/LinkComponent.jsx
> +            to={props.href}
La prop `href` podría renombrarse a `to` para mantener la misma interfaz que el compoente `Link`

2021-10-28 20:34 UTC, MatiasOlivera requested changes

2021-10-28 20:34 UTC, MatiasOlivera commented on src/components/LinkComponent/LinkComponent.jsx
> +import React from 'react';
Se deberían formatear los archivos con Prettier

2021-11-06 11:31 UTC, leoachear commented on src/components/LinkComponent/LinkComponent.module.css
> +.toLogin {
👍

2021-11-06 11:32 UTC, leoachear commented on src/components/LinkComponent/LinkComponent.jsx
> +            to={props.href}
👍

2021-11-06 11:33 UTC, leoachear commented on src/components/LinkComponent/LinkComponent.jsx
> +import React from 'react';
@MatiasOlivera esto si no recuerdo mal habíamos hablado de ver la forma de que todos usemos la misma configuración ¿no? 🤔

2021-11-06 23:27 UTC, MatiasOlivera commented on src/components/LinkComponent/LinkComponent.jsx
> +import React from 'react';
Si, la configuración de Prettier está definida en el archivo `.prettierrc.json` y las extensiones buscan/usan ese archivo

2021-11-06 23:31 UTC, MatiasOlivera commented on src/components/LinkComponent/LinkComponent.module.css
> +.toLogin {
Falta resolver este tema, actualmente la clase se llama `login` y deberia llamarse `link`

2021-11-09 22:37 UTC, leoachear commented on src/components/LinkComponent/LinkComponent.module.css
> +.toLogin {
¡Listo! 👍

2021-11-17 01:25 UTC, SebasEC96 approved these changes
LGTM

2021-11-17 01:26 UTC, SebasEC96 commented
@leoachear Cuando puedas mirate los conflictos así vamos mergeando, saludos!

2021-11-18 13:38 UTC, merged

2021-11-18 13:40 UTC, leoachear commented
@SebasEC96 ya resolví los conflictos 👍