features/MobileNavbar-Component
frontendcafe/cmyk-mango pull request #91
Opened 2021-10-22 13:25 UTC by leoachear

👉  Falta agregar las rutas a los links.

2021-10-28 21:22 UTC, MatiasOlivera requested changes

2021-10-28 21:22 UTC, MatiasOlivera commented on src/assets/images/perfil.svg
> +<svg width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
El archivo `perfil` debería llamarse `profile`, ya que estamos usando los nombres en inglés

2021-10-28 21:22 UTC, MatiasOlivera commented on src/components/MobileNavbar/MobileNavbar.jsx
> +        <div className={ styles["footer"] }>
```suggestion
        <footer className={ styles["footer"] }>
```
Se podría usar la etiqueta `footer`

2021-10-28 21:22 UTC, MatiasOlivera commented on src/components/MobileNavbar/MobileNavbar.jsx
> +                    <a id="new-meeting" href="">
Se deberían eliminar los ids `new-meeting`, `perfil` y `my-meetings` porque no se están usando y no se van a usar

2021-10-28 21:22 UTC, MatiasOlivera commented on src/components/MobileNavbar/MobileNavbar.jsx
> +                    <a id="perfil" href="">
Se debería usar el componente `Link` de React Router en vez de la etiqueta `a` porque las rutas de la SPA son resueltas por React Router

2021-10-28 21:22 UTC, MatiasOlivera commented on src/components/MobileNavbar/MobileNavbar.jsx
> +                    <a id="my-meetings" href="">
Actualmente se puede ir a otra página haciendo click sobre el ícono, si se hace click sobre el texto no funciona. Estaria bueno que el hitbox del link sea el contenedor, ya que al ser más grande no es necesario ser tan preciso

2021-10-28 21:22 UTC, MatiasOlivera commented on src/components/MobileNavbar/MobileNavbar.module.css
> +body {
Los estilos de `body` deberían estar en el archivo `App.css`, ya que afectan a la aplicación y no al componente

2021-10-28 22:33 UTC, leoachear commented on src/assets/images/perfil.svg
> +<svg width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
👍

2021-11-06 11:03 UTC, leoachear commented on src/components/MobileNavbar/MobileNavbar.jsx
> +        <div className={ styles["footer"] }>
👍

2021-11-06 11:04 UTC, leoachear commented on src/components/MobileNavbar/MobileNavbar.jsx
> +                    <a id="new-meeting" href="">
👍

2021-11-06 11:07 UTC, leoachear commented on src/components/MobileNavbar/MobileNavbar.jsx
> +                    <a id="perfil" href="">
👍

2021-11-06 11:08 UTC, leoachear commented on src/components/MobileNavbar/MobileNavbar.jsx
> +                    <a id="perfil" href="">
👍

2021-11-06 11:22 UTC, leoachear commented on src/components/MobileNavbar/MobileNavbar.jsx
> +                    <a id="my-meetings" href="">
👍

2021-11-06 11:23 UTC, leoachear commented on src/components/MobileNavbar/MobileNavbar.module.css
> +body {
👍

2021-11-06 23:47 UTC, MatiasOlivera approved these changes
Excelente Leo! :tada:

2021-11-06 23:47 UTC, merged